---
- name: Install Elasticsearch
  hosts: elasticsearch
  roles:
    - { role: elastic }

- name: Install Kibana
  hosts: kibana
  roles:
    - { role: kibana-role }

- name: Install Filebeat
  hosts: app
  roles:
    - { role: filebeat-role }