---

- name: Synchronization
  copy:
      src: ./
      dest: "{{ path }}/"
      owner: root
      group: root
      mode: 0644

- name: Sync to {{ path }}
  template:
    src: docker-compose.yml.j2
    dest: "{{ path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: Ensures {{postgresql_data_path}} dir exists
  file: path={{postgresql_data_path}} state=directory

- name: Ensures {{postgresql_backup_path}} dir exists
  file: path={{postgresql_backup_path}} state=directory

- name: Pull all images in compose
  command: docker-compose -f "{{ path }}/docker-compose.yml" pull

- name: Up all services in compose
  command: docker-compose -f "{{ path }}/docker-compose.yml" up -d --build