---
  - name: Install of Requrements Tools
    hosts: test
    become: yes
    become_user: root
    remote_user: ops
    roles:
      - role: install-tools
      - role: docker-installation
      - role: postgres
        vars:
          postgresql_port      : '5432'
          postgresql_data_path : '/opt/postgres_data'
          version: "13.0"