---
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Installing docker package
    package: >
      package={{ item }}
      state=present
      update_cache=yes
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Enable docker daemon
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install docker-compose
    raw: $(curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose)

