#  docker build -t almaznv/elastic:1.0 .
#  docker run -d -p 9200:9200 almaznv/elastic:1.0

---
  - name: Install of Requrements Tools
    hosts: test
    become: yes
    become_user: root
    remote_user: ops
    roles:
      - role: install-tools
      - role: docker-installation