apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: http
      protocol: TCP
      name: http{{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{ end }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
