apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
          - name: POSTGRES_DB
            value: "news"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod-netology-front
  name: prod-netology-front
  namespace: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-netology-front
  template:
    metadata:
      labels:
        app: prod-netology-front
    spec:
      imagePullSecrets:
        - name: netologyregistry
      containers:
      - image: cr.yandex/crpaknp5iglnaki6hnq7/frontend:latest1
        name: frontend
        ports:
          - name: front
            containerPort: 80
        env:
          - name: BASE_URL
            value: "http://51.250.22.68:32009"
---
apiVersion: v1
kind: Service
metadata:
  name: prod-netology-front
spec:
  selector:
    app: prod-netology-front
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: front
      nodePort: 32008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod-netology-backend
  name: prod-netology-backend
  namespace: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-netology-backend
  template:
    metadata:
      labels:
        app: prod-netology-backend
    spec:
      imagePullSecrets:
        - name: netologyregistry
      containers:
      - image: cr.yandex/crpaknp5iglnaki6hnq7/backend:latest
        name: backend
        ports:
          - name: back
            containerPort: 9000
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@postgres.netology.svc.cluster.local:5432/news
---
apiVersion: v1
kind: Service
metadata:
  name: prod-netology-backend
spec:
  selector:
    app: prod-netology-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: back
      nodePort: 32009